-- ============================================================
-- IntegroAI — Growth Playbooks schema (Agent 04)
-- Additive migration. Run AFTER schema.sql in the Supabase SQL Editor.
-- Safe to re-run (idempotent).
-- ============================================================

-- Shared updated_at trigger — defined again here (create or replace is
-- idempotent) so this file doesn't require outbound-schema.sql to have
-- run first.
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Playbooks ----------------------------------------------------
--   A playbook is a named set of "plays" (tactical guidance) for a
--   revenue motion. Created manually, or generated by the Growth
--   Playbooks agent from connected CRM win/loss data or from live web
--   research (source records which).
create table if not exists public.playbooks (
  id                  uuid primary key default gen_random_uuid(),
  user_id             uuid not null references auth.users(id) on delete cascade,
  title               text not null,
  description         text not null default '',
  category            text not null default 'General',
  status              text not null default 'draft',   -- draft | active | archived
  source              text not null default 'manual',  -- manual | ai_crm | ai_web
  plays               jsonb not null default '[]',      -- [{ id, title, description }]
  win_rate_pct        numeric,
  avg_deal_cycle_days integer,
  tags                text[] not null default '{}',
  sources_used        jsonb not null default '[]',      -- [{ title, url }] — web citations
  crm_summary         text,                              -- CRM stats snapshot used at generation time
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

alter table public.playbooks enable row level security;

drop policy if exists "own playbooks" on public.playbooks;
create policy "own playbooks" on public.playbooks for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

create index if not exists playbooks_user_idx   on public.playbooks (user_id, created_at desc);
create index if not exists playbooks_status_idx on public.playbooks (user_id, status);

drop trigger if exists playbooks_updated_at on public.playbooks;
create trigger playbooks_updated_at before update on public.playbooks
  for each row execute procedure public.set_updated_at();
